name: Build for Release

on:
  push:
    branches: [ ci* ]

jobs:
  build-win:
    name: Build for win
    runs-on: windows-latest
      steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ci-v1
      - id: setup-jdk
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
      - id: build
        name: Build distribution
        run: |
          python build.py
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: ./out/Shutter Encoder-0.1.exe
          name: windows-installer
          retention-days: 1
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-win]
    steps:
      - id: download-windows-installer
        name: Download Windows installer
          uses: actions/download-artifact@v3
        with:
          name: windows-installer

  - id: rename-downloaded-files
    name: Rename downloaded files
  - id: tag
    name: Move example-release tag
    shell: bash
    if: false
    run: |
      # Move tag
      git tag -d example-release
      git push --delete origin example-release
      git tag -a example-release -m "Example of a Release"
      git push --follow-tags
  - id: create-release
    name: Create GitHub release
    uses: actions/create-release@latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      tag_name: example-release
      release_name: example-release
      draft: false
      prerelease: false
  - id: release-windows-installer
    name: Release Windows installer
    uses: actions/upload-release-asset@latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      asset_path: Shutter Encoder-0.1.exe
      asset_name: Shutter Encoder-0.1.exe
      asset_content_type: application/x-binary
